[package]
name = "todo-list"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = { version = "0.7.5", features = ["date"] }
chrono = {version = "0.4.40", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.140"
crossterm = "0.29.0"
